# ansible/roles/docker/vars/main.yaml

# Docker prerequisites
docker_prerequisites:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg-agent
  - software-properties-common

# Docker GPG key URL
docker_gpg_key_url: "https://download.docker.com/linux/ubuntu/gpg"

# Docker APT repository
docker_apt_repository: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"

# Docker packages
docker_ce_package: "docker-ce"
docker_compose_package: "docker-compose"

# Docker service name
docker_service_name: "docker"

# Docker socket settings
docker_socket_path: "/var/run/docker.sock"
docker_socket_owner: "root"
docker_socket_group: "docker"
docker_socket_mode: "0660"
