# ansible/roles/java_jenkins/tasks/main.yaml

---
- name: Install Java
  apt:
    name: "{{ java_package }}"
    state: present

- name: Create Jenkins user
  user:
    name: "{{ jenkins_user }}"
    shell: "{{ jenkins_shell }}"
    create_home: yes

- name: Create Jenkins agent directory
  file:
    path: "{{ jenkins_agent_dir }}"
    state: directory
    owner: "{{ jenkins_user }}"
    group: "{{ jenkins_user }}"
    mode: '0755'

- name: Download Jenkins agent jar
  get_url:
    url: "{{ jenkins_agent_jar_url }}"
    dest: "{{ jenkins_agent_jar_path }}"
    mode: '0755'

- name: Create Jenkins var folder
  file:
    path: "{{ jenkins_home }}"
    state: directory
    owner: "{{ jenkins_user }}"
    group: "{{ jenkins_user }}"
    mode: '0755'

- name: Check if Jenkins agent is already running
  shell: pgrep -f "java -jar {{ jenkins_agent_jar_path }}" || echo "not running"
  register: agent_status
  changed_when: false

- name: Run Jenkins agent in background
  shell: >
    nohup java -jar {{ jenkins_agent_jar_path }}
    -url {{ jenkins_server_url }}
    -secret {{ jenkins_agent_secret }}
    -name {{ jenkins_agent_name }}
    -workDir "{{ jenkins_work_dir }}" &
  args:
    chdir: "{{ jenkins_work_dir }}"
  when: agent_status.stdout == "not running"
