---
- name: Install AWS CLI v2 on Ubuntu
  become: yes
  block:
    - name: Check if AWS CLI v2 is installed
      command: "{{ awscli_version_command }}"
      register: aws_version
      ignore_errors: yes

    - name: Install AWS CLI v2 if not installed
      block:
        - name: Download AWS CLI v2
          get_url:
            url: "{{ awscli_download_url }}"
            dest: "{{ awscli_download_dest }}"

        - name: Unzip AWS CLI v2
          unarchive:
            src: "{{ awscli_download_dest }}"
            dest: "{{ awscli_unzip_dest }}"
            remote_src: yes

        - name: Install AWS CLI v2
          command: "{{ awscli_install_command }}"

        - name: Remove the installer and zip file
          file:
            path: "{{ item }}"
            state: absent
          loop:
            - "{{ awscli_download_dest }}"
            - "{{ awscli_unzip_dest }}/aws"
      when: aws_version is failed
