---
- name: Install AWS CLI v2 on Ubuntu
  become: yes
  block:
    - name: Check if AWS CLI v2 is installed
      command: aws --version
      register: aws_version
      ignore_errors: yes

    - name: Install AWS CLI v2 if not installed
      block:
        - name: Download AWS CLI v2
          get_url:
            url: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
            dest: /tmp/awscliv2.zip

        - name: Unzip AWS CLI v2
          unarchive:
            src: /tmp/awscliv2.zip
            dest: /tmp/
            remote_src: yes

        - name: Install AWS CLI v2
          command: /tmp/aws/install

        - name: Remove the installer and zip file
          file:
            path: "{{ item }}"
            state: absent
          loop:
            - /tmp/awscliv2.zip
            - /tmp/aws/
      when: aws_version is failed
