---
- name: Install kubectl in machine
  become: yes
  block:
    - name: Download kubectl binary
      get_url:
        url: "{{ kubectl_download_url }}"
        dest: "{{ kubectl_dest }}"
        mode: "{{ kubectl_mode }}"

    - name: Verify kubectl binary
      command: "{{ kubectl_version_command }}"
      register: kubectl_version_result
      changed_when: false
      failed_when: "'Client Version:' not in kubectl_version_result.stdout"
