apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpine-deployment
  namespace: apps
  labels:
    app: alpine
spec:
  replicas: 5
  selector:
    matchLabels:
      app: alpine
  template:
    metadata:
      labels:
        app: alpine
    spec:
      containers:
      - name: alpine
        image: alpine:latest
        resources:
          requests:
            memory: "2Gi"
          limits:
            memory: "2Gi"
        command: ["/bin/sh", "-c", "while true; do sleep 3600; done"]
