---
- name: Install prerequisites for Docker
  apt:
    name: "{{ docker_prerequisites }}"
    state: present

- name: Add Docker’s official GPG key
  apt_key:
    url: "{{ docker_gpg_key_url }}"
    state: present

- name: Add Docker APT repository
  apt_repository:
    repo: "{{ docker_apt_repository }}"
    state: present

- name: Update apt package index after adding Docker repo
  apt:
    update_cache: yes

- name: Install Docker CE
  apt:
    name: "{{ docker_ce_package }}"
    state: present

- name: Install Docker Compose
  apt:
    name: "{{ docker_compose_package }}"
    state: present

- name: Ensure Docker service is running
  systemd:
    name: "{{ docker_service_name }}"
    enabled: yes
    state: started

- name: Set correct ownership and permissions for Docker socket
  block:
    - name: Change ownership of Docker socket
      file:
        path: "{{ docker_socket_path }}"
        owner: "{{ docker_socket_owner }}"
        group: "{{ docker_socket_group }}"
        mode: "{{ docker_socket_mode }}"

    - name: Change permissions of Docker socket
      command: "chmod {{ docker_socket_mode }} {{ docker_socket_path }}"
      become: yes

- name: Add current user to the Docker group
  user:
    name: "{{ ansible_user_id }}"
    groups: docker
    append: yes
