---
- name: Install prerequisites for Docker
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
    state: present

- name: Add Docker’s official GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker APT repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present

- name: Update apt package index after adding Docker repo
  apt:
    update_cache: yes

- name: Install Docker CE
  apt:
    name: docker-ce
    state: present

- name: Install Docker Compose
  apt:
    name: docker-compose
    state: present

- name: Ensure Docker service is running
  systemd:
    name: docker
    enabled: yes
    state: started

- name: Set correct ownership and permissions for Docker socket
  block:
    - name: Change ownership of Docker socket
      file:
        path: /var/run/docker.sock
        owner: root
        group: docker
        mode: '0660'
    
    - name: Change permissions of Docker socket
      command: sudo chmod 660 /var/run/docker.sock
      become: yes

- name: Add current user to the Docker group
  user:
    name: "{{ ansible_user_id }}"
    groups: docker
    append: yes
